home/urls.py
from django.conf.urls import url, include
from .views import index, contactSubmit

app_name = 'home'

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^contact/submit/$', contactSubmit, name='contactSubmit'),

]

log/urls.py
from django.conf.urls import url

from . import views

app_name = 'log'

urlpatterns = [
	# url(r'^login/$', login, name='login'),
	# url(r'^logout/$', logout, name='logout'),
	# url(r'^register/$', register, name='register'),
	# url(r'^login/$', user_login, name='login'),
	# url(r'^logout/$', user_logout, name='logout'),
	# url(r'^dashboard/$', dashboard, name='dashboard'),
	# url(r'^dashboard/messages/$', messages, name='messages'),
	# url(r'^dashboard/blogs/$', blogs, name='blogs'),

	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/$', BlogDetailView.as_view(), name='blog-detail'),

	# url(r'^dashboard/events/$', events, name='events'),
	# url(r'^dashboard/blogs/add/$', post_new, name='blog-add'),
	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/edit$', post_edit , name='blog-edit'),
	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/delete$', BlogDelete.as_view() , name='blog-delete'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^dashboard/messages/$', views.messages, name='messages'),
	url(r'^dashboard/blogs/$', views.blogs, name='blogs'),
	url(r'^dashboard/info/$', views.info, name='info'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/$', views.InfoDetailView.as_view(), name='info-detail'),

	url(r'^dashboard/team/$', views.team, name='team'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/$', views.TeamDetailView.as_view(), name='team-detail'),

	url(r'^dashboard/events/$', views.events, name='events'),


	url(r'^dashboard/blogs/add/$', views.post_new, name='blog-add'),
	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/edit$', views.post_edit , name='blog-edit'),
	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/delete$', views.BlogDelete.as_view() , name='blog-delete'),

	url(r'^dashboard/info/add/$', views.info_new, name='info-add'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/edit$', views.info_edit , name='info-edit'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/delete$', views.InfoDelete.as_view() , name='info-delete'),

	url(r'^dashboard/team/add/$', views.team_new, name='team-add'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/edit$', views.team_edit , name='team-edit'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/delete$', views.TeamDelete.as_view() , name='team-delete'),

	url(r'^dashboard/events/add/$', views.event_new, name='event-add'),
	url(r'^dashboard/events/(?P<slug>[\w-]+)/edit$', views.event_edit , name='event-edit'),
	url(r'^dashboard/events/(?P<slug>[\w-]+)/delete$', views.EventDelete.as_view() , name='event-delete'),

	url(r'^dashboard/events/(?P<slug>[\w-]+)/$', views.EventDetailView.as_view(), name='event-detail'),

	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/$', views.BlogDetailView.as_view(), name='blog-detail'),

	# url(r'^dashboard/$',),

]

techspace/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^codeschool/', include('codeschool.urls')),
    url(r'^cogitans/', include('cogitans.urls')),
    url(r'^droidclub/', include('droidclub.urls')),
    url(r'^ecell/', include('ecell.urls')),
    url(r'^electrotech/', include('electrotech.urls')),
    url(r'^oslc/', include('oslc.urls')),
    url(r'^renderedusict/', include('renderedusict.urls')),
    url(r'^turingai/', include('turingai.urls')),
    url(r'^', include('home.urls')),
    url(r'^accounts/', include('log.urls')),
    url(r'^blogs/', include('blog.urls')),
    url(r'^events/', include('event.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from django.core.urlresolvers import reverse


# Create your models here.

class BlogPost(models.Model):
	author = models.CharField(max_length=255)
	date = models.DateTimeField(default=datetime.now)
	title = models.CharField(max_length=1024, unique=True)
	image = models.ImageField(upload_to='blog', default='blog/thumbnail-default.jpg')
	content = models.TextField()
	slug = models.SlugField(_('slug'), db_index=True, max_length=2024, unique=True)


	codeschool = 'codeschool'
	cogitans = 'cogitans'
	droidclub = 'droidclub'
	ecell = 'ecell'
	electrotech = 'electrotech'
	oslc = 'oslc'
	renderedusict = 'renderedusict'
	turingai = 'turingai'

	club_choices = (
			(codeschool, 'Codeschool'),
			(cogitans, 'Cogitans'),
			(droidclub, 'Droid Club'),
			(ecell, 'E-Cell'),
			(electrotech, 'Electrotech'),
			(oslc, 'OSLC'),
			(renderedusict, 'Rendered-USICT'),
			(turingai, 'Turing A.I.'),

		)

	club = models.CharField(max_length=200, choices=club_choices, blank=True)

	def get_absolute_url(self):
		return reverse('blog:detail', args=[self.id, self.slug])


	def save(self, *args,**kwargs):
		if not self.id:
			self.slug = slugify(self.title)
		super(BlogPost, self).save(*args, **kwargs)


	def __str__(self):
		return self.title + ' - ' + self.author + ' - ' + self.get_club_display()

class Comments(models.Model):
	post = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
	comment_author = models.CharField(max_length=200)
	comment_text = models.TextField()
	comment_date = models.DateTimeField(default=datetime.now)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.post.title + ' - ' + self.comment_author

log/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
	user = models.OneToOneField(User)

	club_choice = (
		('none', 'none'),
		('codeschool', 'codeschool'),
		('cogitans', 'cogitans'),
		('ecell', 'ecell'),
		('electrotech', 'electrotech'),
		('oslc', 'oslc'),
		('renderedusict', 'renderedusict'),
		('turingai', 'turingai'),
		('techspace', 'techspace')
	)

	club = models.CharField(max_length=255, choices=club_choice, default='none')

	def __str__(self):
		return self.user.username

log/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login ,logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.exceptions import ValidationError, PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from django.views.generic import DetailView
from django.views.generic.edit import DeleteView

from .forms import UserForm, UserProfileForm, BlogAddForm, InfoAddForm, TeamAddForm, EventAddForm
from home.models import Contact, Info, Team
from blog.models import BlogPost
from event.models import Events
from .models import UserProfile

# Create your views here.

def register(request):
	registered = False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid() :
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()


			registered = True
			return HttpResponseRedirect(reverse('log:login'))
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	return render(request, 'registration/user_register.html', {'registered':registered, 'user_form': user_form, 'profile_form': profile_form})


def user_login(request):
	if request.method == 'POST':
		username = request.POST.get("username")
		password = request.POST.get("password")

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('log:dashboard'))
			else:
				return HttpResponse("Account is not active")
		else:
			print("someone tried to login with wrong credentials")

			return HttpResponse("invalid credentials")
	else:
		return render(request, 'registration/login.html', {})


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home:index'))



@login_required
def dashboard(request):
	userprofile = UserProfile.objects.get(user=request.user)
	return render(request, 'log/dashboard.html', {'userprofile': userprofile})



@login_required
def messages(request):
	user = UserProfile.objects.get(user=request.user)
	contacts = Contact.objects.filter(app_name=user.club)
	return render(request, 'log/contact_dashboard.html', {'contacts': contacts})


@login_required
def info(request):
	user = UserProfile.objects.get(user=request.user)
	info = Info.objects.filter(club=user.club)
	return render(request, 'log/info_dashboard.html', {'info': info})


class InfoDetailView(LoginRequiredMixin, DetailView):
	model = Info
	template_name = 'log/infodetail_dashboard.html'
	context_object_name = 'info_detail'


@login_required
def events(request):
	user = UserProfile.objects.get(user=request.user)
	events = Events.objects.filter(club=user.club)
	return render(request, 'log/event_dashboard.html', {'events': events})


class EventDetailView(LoginRequiredMixin, DetailView):
	model = Events
	template_name = 'log/eventdetail_dashboard.html'
	context_object_name = 'event_detail'


@login_required
def team(request):
	user = UserProfile.objects.get(user=request.user)
	team = Team.objects.filter(club=user.club)
	return render(request, 'log/team_dashboard.html', {'team': team})

class TeamDetailView(LoginRequiredMixin, DetailView):
	model = Team
	template_name = 'log/teamdetail_dashboard.html'
	context_object_name = 'team_detail'


@login_required
def blogs(request):
	user = UserProfile.objects.get(user=request.user)

	if user.club == 'techspace':
		blogs = BlogPost.objects.all()

	else:
		blogs = BlogPost.objects.filter(club=user.club)

	return render(request, 'log/blog_dashboard.html', {'blogs': blogs})


class BlogDetailView(LoginRequiredMixin, DetailView):
	model = BlogPost
	template_name = 'log/blogdetail_dashboard.html'
	context_object_name = 'blog_detail'


@login_required
def events(request):
	user = UserProfile.objects.get(user=request.user)

	if user.club == 'techspace':
		events = Events.objects.all()

	else:
		events = Events.objects.filter(club=user.club)

	return render(request, 'log/event_dashboard.html', {'events': events})




# class BlogCreate(CreateView):
# 	model = BlogPost
# 	fields = ['author', 'title', 'image', 'content', 'club']

@login_required
def event_new(request):
	if request.method == 'POST':
		form = EventAddForm(request.POST)
		user = UserProfile.objects.get(user=request.user)
		if form.is_valid():
			event = form.save(commit=False)
			event.club = user.club
			event.author = str(user)
			event.save()
			return redirect('log:event-detail', slug=event.slug)

	form = EventAddForm()
	return render(request, 'log/eventadd_form.html', {'form': form})


@login_required
def event_edit(request, slug):
	user = UserProfile.objects.get(user=request.user)
	event = get_object_or_404(Events, slug=slug)
	if user.club == event.club:
		if request.method == 'POST':
			form = EventAddForm(request.POST, instance=event)
			if form.is_valid():
				event = form.save(commit=False)
				event.club = user.club
				event.save()
				return redirect('log:event-detail', slug=event.slug)

		form = EventAddForm(instance=event)
		return render(request, 'log/eventedit_form.html', {'form': form})

	else:
		return redirect('home:index')


class EventDelete(LoginRequiredMixin, DeleteView):
	model = Events
	success_url = reverse_lazy('log:events')
	def get_object(self, queryset=None):
		event = super(EventDelete,self).get_object()
		user = UserProfile.objects.get(user=self.request.user)
		if event.club == user.club:
			return event
		raise Http404



@login_required
def post_new(request):
	if request.method == "POST":
		form = BlogAddForm(request.POST, request.FILES)
		user = UserProfile.objects.get(user=request.user)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = user.user.username
			post.club = user.club

			if 'image' in request.FILES:
				post.image = request.FILES['image']

			post.save()
			return redirect('blog:detail', slug=post.slug)


	form = BlogAddForm()
	return render(request, 'log/blogadd_form.html', {'form':form})


@login_required
def post_edit(request, slug):
	user = UserProfile.objects.get(user=request.user)
	post = get_object_or_404(BlogPost, slug=slug)
	if user.club == post.club:
		if request.method == "POST":
			form = BlogAddForm(request.POST, request.FILES ,instance=post)

			if form.is_valid():
				post = form.save(commit=False)
				post.author = str(user)
				post.club = str(user.club)
				post.date = timezone.now()

				if 'image' in request.FILES:
					post.image = request.FILES['image']

				post.save()
				return redirect('log:blog-detail', slug=post.slug)

		form = BlogAddForm(instance=post)
		return render(request, 'log/blogedit_form.html', {'form': form})

	else:
		return redirect('home:index')


class BlogDelete(LoginRequiredMixin, DeleteView):
	model = BlogPost
	success_url = reverse_lazy('log:blogs')

	def get_object(self, queryset=None):
		blog = super(BlogDelete,self).get_object()
		user = UserProfile.objects.get(user=self.request.user)
		if blog.club == user.club:
			return blog
		raise Http404


@login_required
def info_new(request):
	if request.method == "POST":
		form = InfoAddForm(request.POST)
		user = UserProfile.objects.get(user=request.user)
		if form.is_valid():
			info = form.save(commit=False)
			info.author = str(user)
			info.club = user.club
			info.save()
			return redirect('log:info-detail', pk=info.pk)

	form = InfoAddForm()
	return render(request, 'log/infoadd_form.html', {'form': form})


@login_required
def info_edit(request, pk):
	user = UserProfile.objects.get(user=request.user)
	info = get_object_or_404(Info, pk=pk)
	if info.club == user.club:
		if request.method == 'POST':
			form = InfoAddForm(request.POST, instance=info)

			if form.is_valid():
				info = form.save(commit=False)
				info.author = str(user)
				info.club = user.club
				info.save()
				return redirect('log:info-detail', pk=info.pk)

		form = InfoAddForm(instance=info)
		return render(request, 'log/infoedit_form.html', {'form': form})

	else:
		return redirect('home:index')



class InfoDelete(LoginRequiredMixin, DeleteView):
	model = Info
	success_url = reverse_lazy('log:info')
	def get_object(self, queryset=None):
		info = super(InfoDelete,self).get_object()
		user = UserProfile.objects.get(user=self.request.user)
		if info.club == user.club:
			return blog
		raise Http404


@login_required
def team_new(request):
	if request.method == 'POST':
		form = TeamAddForm(request.POST)
		user = UserProfile.objects.get(user=request.user)
		if form.is_valid():
			team = form.save(commit=False)
			team.club = user.club
			team.save()
			return redirect('log:team-detail', pk=info.pk)

	form = TeamAddForm()
	return render(request, 'log/teamadd_form.html', {'form': form})


@login_required
def team_edit(request, pk):
	user = UserProfile.objects.get(user=request.user)
	team = get_object_or_404(Team, pk=pk)
	if user.club == team.club:
		if request.method == 'POST':
			form = InfoAddForm(request.POST, instance=team)

			if form.is_valid():
				team = form.save(commit=False)
				team.club = user.club
				team.save()
				return redirect('log:team-detail', pk=team.pk)

		form = InfoAddForm(instance=team)
		return render(request, 'log/teamedit_form.html', {'form': form})

	else:
		return redirect('home:index')


class TeamDelete(LoginRequiredMixin, DeleteView):
	model = Team
	success_url = reverse_lazy('log:team')
	def get_object(self, queryset=None):
		team = super(TeamDelete,self).get_object()
		user = UserProfile.objects.get(user=self.request.user)
		if team.club == user.club:
			return team
		raise Http404

templates/log/blogadd_form.html
{% extends './base.html' %}

{% block content %}

<div class="blog-container">

<h1>Add a blog</h1>
<form method="post" class="form-group" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default blog-sub">Submit</button>

</form>
</div>


{% endblock %}

templates/log/blogdetail_dashboard.html
{% extends './base.html' %}

{% block content %}

	{% if blog_detail %}
	<div class="blog_content">
{% if user.username == blog_detail.author %}
	<div class="stack">
		<form action="{% url 'log:blog-edit' blog_detail.slug %}" method="get">
			<button>Edit</button>
		</form>
		<form action="{% url 'log:blog-delete' blog_detail.slug %}" method="post" >
			{% csrf_token %}
			<button>Delete</button>
		</form>
	</div>


		<h1 class="center">{{ blog_detail.title }}</h1>
		<h4 class="center">{{ blog_detail.author }} </h4>
		<h4 class="center">{{ blog_detail.date }} </h4>
				<div class="underline"></div>

		<img class="centre img-responsive blog_image" src="{{ blog_detail.image.url }}">
		<p>{{ blog_detail.content|linebreaks }}</p>

	</div>

	{% else %}
	<h2>You are not authorised to visit this page. Kindly go to <a href="{% url 'home:index' %}">homepage</a>.</h2>
	{% endif %}
	{% else %}
		<h1>Nothing to show</h1>


	{% endif %}


{% endblock %}

templates/log/blogedit_form.html
{% extends './base.html' %}

{% block content %}


	<div class="blog-container">

<h1>Edit your blog</h1>
	<form method="post" class="form-group" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-submit blog-sub">Submit</button>
		
	</form>
		
	</div>


{% endblock %}

templates/log/contact_dashboard.html
{% extends './base.html' %}

{% block content %}


{% if user.is_authenticated %}

<h4>hey, {{ user.username }}</h4>


<div class="">
<table class="table table-bordered" id="table">
<thead>
	<tr>
	<th>Name</th>
	<th>Email</th>
	<th>Message</th>
	</tr>
</thead>


{% for contact in contacts reversed %}

	<tbody>
	<tr>
	<td>{{ contact.name }}</td>
	<td>{{ contact.email }}</td>
	<td>{{ contact.content }}</td>
	</tr>
	</tbody>

{% endfor %}



</table>

</div>




{% else %}
<h1>You need to <a href="{% url 'log:login' %}">login</a> first.</h1>






{% endif %}







{% endblock %}

templates/log/dashboard.html
{% extends './base.html' %}

{% block content %}



{% if user.is_authenticated %}



{% if userprofile.club == 'none' %}
<h4>hey, <b>{{ user.username }}</b></h4>

<a href="{% url 'log:blogs' %}"><h4>Blogs</h4></a>

{% else %}

<h4>hey, <b>{{ user.username }}</b> from <b>{{ userprofile.club }}</b></h4>

<div class="">
<a href="{% url 'log:blogs' %}"><h4>Blogs</h4></a>
<a href="{% url 'log:messages' %}"><h4>Contact forms</h4></a>
<a href="{% url 'log:events' %}"><h4>Events</h4></a>
<a href="{% url 'log:info' %}"><h4>Club Info</h4></a>
<a href="{% url 'log:team' %}"><h4>Team</h4></a>


</div>


{% endif %}


{% else %}
<h1>You need to <a href="{% url 'log:login' %}">login</a> first.</h1>






{% endif %}






{% endblock %}

templates/log/event_dashboard.html
{% extends './base.html' %}

{% block content %}



{% if user.is_authenticated %}

<h4>hey, {{ user.username }}</h4>
<h4>{{ user.club }}</h4>



<h2><a href=" {% url 'log:event-add' %} ">Add Event</a></h2>



{% if events %}
<ul>

	{% for event in events %}
	<li>
		<p><a href="{% url 'log:event-detail' event.slug %}"> {{ event.title }}</a></p>
		<p>{{ event.date }}</p>
	</li>
	{% endfor %}

</ul>

{% else %}

<h4>No events To show</h4>

{% endif %}


{% else %}

<h1>You need to login first!</h1>

{% endif %}



{% endblock %}

templates/log/eventadd_form.html
{% extends './base.html' %}

{% block content %}

 <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
  <script>
  $( function() {
    $( "#id_date" ).datepicker();
  } );



	$(document).ready(function(){
	    $('#id_time').timepicker({
	    	scrollbar: true
	    });
	});


  </script>


<div class="blog-container">
<h1>Add events</h1>
<form method="post" class="form-group">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default blog-sub">Submit</button>

</form>
</div>


{% endblock %}

templates/log/eventdetail_dashboard.html
{% extends './base.html' %}

{% block content %}

<div class="blog-container">


<div class="blog_content">

	{% if event_detail %}

	<div class="stack">
		<form action="{% url 'log:event-edit' event_detail.slug %}" method="get">
			<button>Edit</button>
		</form>
		<form action="{% url 'log:event-delete' event_detail.slug %}" method="post" >
			{% csrf_token %}
			<button>Delete</button>
		</form>
	</div>


		<h1 class="center">{{ event_detail.title }}</h1>
		<h4 class="center">{{ event_detail.date }} </h4>
		<h4 class="center">{{ event_detail.time }} </h4>
		<h4 class="center">{{ event_detail.venue }} </h4>
		<p>{{ event_detail.content|linebreaks }}</p>

</div>
	{% else %}
		<h1>Nothing to show</h1>


	{% endif %}


</div>

{% endblock %}

templates/log/eventedit_form.html
{% extends './base.html' %}

{% block content %}

 <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
  <script>
  $( function() {
    $( "#id_date" ).datepicker();
  } );



	$(document).ready(function(){
	    $('#id_time').timepicker({
	    	scrollbar: true
	    });
	});


  </script>

<div class="blog-container">

	<h1>Edit events</h1>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-default blog-sub">Submit</button>
		
	</form>
		
</div>


{% endblock %}

templates/log/info_dashboard.html
{% extends './base.html' %}

{% block content %}



{% if user.is_authenticated %}

<h4>hey, {{ user.username }}</h4>
<h4>{{ user.club }}</h4>





{% if info %}
<ul>
	
	{% for i in info %}
	<li>
		<p><a href="{% url 'log:info-detail' i.id %}"> {{ i.title }}</a></p>
		<p>{{ i.author }}</p>
	</li>
	{% endfor %}

</ul>

{% else %}
<h2><a href=" {% url 'log:info-add' %} ">Add info</a></h2>

<h4>No info To show</h4>

{% endif %}


{% else %}

<h1>You need to login first!</h1>

{% endif %}



{% endblock %}

templates/log/infoadd_form.html
{% extends './base.html' %}

{% block content %}

<div class="blog-container">

<h1>Add information about your club</h1>
<form method="post" class="form-group">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-default blog-sub">Submit</button>

</form>
</div>


{% endblock %}

templates/log/infodetail_dashboard.html
{% extends './base.html' %}

{% block content %}

<div class="blog-container">

	{% if info_detail %}
	<div class="blog_content">

	<div class="stack">
		<form action="{% url 'log:info-edit' info_detail.pk %}" method="get">
			<button>Edit</button>
		</form>
		<form action="{% url 'log:info-delete' info_detail.pk %}" method="post" >
			{% csrf_token %}
			<button>Delete</button>
		</form>
	</div>
		

		<h1 class="center">{{ info_detail.title }}</h1>
		<h4 class="center">{{ info_detail.author }} </h4>
		<p>{{ info_detail.content|linebreaks }}</p>

	</div>
	{% else %}
		<h1>Nothing to show</h1>


	{% endif %}

</div>
{% endblock %}

templates/log/team_dashboard.html
{% extends './base.html' %}

{% block content %}



{% if user.is_authenticated %}

<h4>hey, {{ user.username }}</h4>
<h4>{{ user.club }}</h4>



<h2><a href=" {% url 'log:team-add' %} ">Add team member</a></h2>



{% if team %}
<ul>
	
	{% for member in team %}
	<li>
		<p><a href="{% url 'log:team-detail' member.id %}"> {{ member.name }}</a></p>
		<img src="{{ member.image.url }}">
		<p>{{ member.designation }}</p>
	</li>
	{% endfor %}

</ul>

{% else %}

<h4>No Member To show</h4>

{% endif %}


{% else %}

<h1>You need to login first!</h1>

{% endif %}



{% endblock %}

templates/log/teamedit_form.html
{% extends './base.html' %}

{% block content %}

	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button>Submit</button>
		
	</form>
		


{% endblock %}