electrotech/urls.py
from django.conf.urls import url
from .views import index, BlogPostView, EventListView

app_name = 'electrotech'

urlpatterns = [
	url(r'^$',index,name='index'),
	url(r'^blog/$', BlogPostView.as_view(), name='post'),
	url(r'^events/$', EventListView.as_view(), name='events'),
]

log/urls.py
from django.conf.urls import url

from . import views

app_name = 'log'

urlpatterns = [
	# url(r'^login/$', login, name='login'),
	# url(r'^logout/$', logout, name='logout'),
	# url(r'^register/$', register, name='register'),
	# url(r'^login/$', user_login, name='login'),
	# url(r'^logout/$', user_logout, name='logout'),
	# url(r'^dashboard/$', dashboard, name='dashboard'),
	# url(r'^dashboard/messages/$', messages, name='messages'),
	# url(r'^dashboard/blogs/$', blogs, name='blogs'),

	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/$', BlogDetailView.as_view(), name='blog-detail'),

	# url(r'^dashboard/events/$', events, name='events'),
	# url(r'^dashboard/blogs/add/$', post_new, name='blog-add'),
	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/edit$', post_edit , name='blog-edit'),
	# url(r'^dashboard/blogs/(?P<pk>[0-9]+)/delete$', BlogDelete.as_view() , name='blog-delete'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^dashboard/messages/$', views.messages, name='messages'),
	url(r'^dashboard/blogs/$', views.blogs, name='blogs'),
	url(r'^dashboard/info/$', views.info, name='info'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/$', views.InfoDetailView.as_view(), name='info-detail'),

	url(r'^dashboard/team/$', views.team, name='team'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/$', views.TeamDetailView.as_view(), name='team-detail'),

	url(r'^dashboard/events/$', views.events, name='events'),


	url(r'^dashboard/blogs/add/$', views.post_new, name='blog-add'),
	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/edit$', views.post_edit , name='blog-edit'),
	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/delete$', views.BlogDelete.as_view() , name='blog-delete'),

	url(r'^dashboard/info/add/$', views.info_new, name='info-add'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/edit$', views.info_edit , name='info-edit'),
	url(r'^dashboard/info/(?P<pk>[0-9]+)/delete$', views.InfoDelete.as_view() , name='info-delete'),

	url(r'^dashboard/team/add/$', views.team_new, name='team-add'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/edit$', views.team_edit , name='team-edit'),
	url(r'^dashboard/team/(?P<pk>[0-9]+)/delete$', views.TeamDelete.as_view() , name='team-delete'),

	url(r'^dashboard/events/add/$', views.event_new, name='event-add'),
	url(r'^dashboard/events/(?P<slug>[\w-]+)/edit$', views.event_edit , name='event-edit'),
	url(r'^dashboard/events/(?P<slug>[\w-]+)/delete$', views.EventDelete.as_view() , name='event-delete'),

	url(r'^dashboard/events/(?P<slug>[\w-]+)/$', views.EventDetailView.as_view(), name='event-detail'),

	url(r'^dashboard/blogs/(?P<slug>[\w-]+)/$', views.BlogDetailView.as_view(), name='blog-detail'),

	# url(r'^dashboard/$',),

]

techspace/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^codeschool/', include('codeschool.urls')),
    url(r'^cogitans/', include('cogitans.urls')),
    url(r'^droidclub/', include('droidclub.urls')),
    url(r'^ecell/', include('ecell.urls')),
    url(r'^electrotech/', include('electrotech.urls')),
    url(r'^oslc/', include('oslc.urls')),
    url(r'^renderedusict/', include('renderedusict.urls')),
    url(r'^turingai/', include('turingai.urls')),
    url(r'^', include('home.urls')),
    url(r'^accounts/', include('log.urls')),
    url(r'^blogs/', include('blog.urls')),
    url(r'^events/', include('event.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electrotech/models.py
from django.db import models

# Create your models here.

electrotech/views.py
from django.shortcuts import render

from blog.models import BlogPost
from blog.views import BlogListView
from event.models import Events 
from event.views import EventView 
from home.models import Info, Team

# Create your views here.

def index(request):
	info = Info.objects.filter(club=Info.electrotech).order_by('id').last()
	team = Team.objects.filter(club=Team.electrotech)
	event = Events.objects.filter(club=Events.electrotech).order_by('-date').first()
	return render(request,'electrotech/index.html', {'info':info, 'team': team, 'event': event})


class BlogPostView(BlogListView):

	def get_context_data(self,**kwargs):
		context = super(BlogPostView,self).get_context_data(**kwargs)
		context['club_blogs'] = BlogPost.objects.filter(club=BlogPost.electrotech)
		return context


class EventListView(EventView):

	def get_context_data(self,**kwargs):
		context = super(EventListView,self).get_context_data(**kwargs)
		context['club_events'] = Events.objects.filter(club=Events.electrotech)
		return context

templates/electrotech/index.html
{% extends 'club_base/base.html' %}

{% block title %}Electrotech{% endblock %}

{% block content %}

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="#">Electrotech <span>- Techspace</span></a></div>
				<a href="#menu"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="#">Home</a></li>
					<li><a href="#one">About</a></li>
					<li><a href="#two">Blogs</a></li>
					<li><a href="#three">Our Team</a></li>
					<li><a href="#four">Events</a></li>
				</ul>
			</nav>

			<section id="banner" class="bg-img" data-bg="{% static 'img/electrotech/banner.jpg' %}">
				<div class="inner">
					<header>
						<h1>Electrotech</h1>
					</header>
				</div>
				<a href="#one" class="more">Learn More</a>
			</section>

		<!-- One -->
			<section id="one" class="wrapper post bg-img" data-bg="{% static 'img/electrotech/banner2.jpg' %}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>About</h2>
						</header>
						<div class="content">
							
							<p>{{info.last.content}}</p>
							
						</div>
						
					</article>
				</div>
				<a href="#two" class="more">Learn More</a>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper post bg-img" data-bg="{% static 'img/electrotech/banner3.jpg' %}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>Blogs</h2>
						</header>
						<div class="content">
							<h3>Click the link below to read our blogs.</h3>
						</div>
						<footer>
							<a href="{% url 'electrotech:post' %}" class="button alt">Blogs</a>
						</footer>
					</article>
				</div>
				<a href="#three" class="more">Learn More</a>
			</section>

		<!-- Three -->


		<style>
			#myCarousel {max-width: 100%;}
			.carousel-inner .active.left  { left: -33%;             }
			.carousel-inner .active.right { left: 33%;              }
			.carousel-inner .next         { left: 33%               }
			.carousel-inner .prev         { left: -33%              }
			.carousel-control.left        { background-image: none; }
			.carousel-control.right       { background-image: none; }
			/*.carousel-inner .item         { background: white;      }*/
			.member-img {
				height: 300px;
				width: 300px;
			}

		</style>

			<section id="three" class="wrapper post bg-img" data-bg="{% static 'img/electrotech/banner4.jpg' %}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>Our Team</h2>
						</header>
						<div class="content">
						    <div id="myCarousel" class="carousel slide container">
						        <div class="carousel-inner">
							        {% for member in team %}
	  									
									  {% if forloop.counter == 1 %}
									    <div class="item active">
									      <div class="col-xs-4">
									      	<img src="{{ member.image.url }}" class="member-img img-responsive">
									      	<span>{{ member.name }}</span><br>
									      	<span>{{ member.designation }}</span><br><br>
									      	<ul style="display: inline;">
									      		<li style="display: inline;"><a href="{{ member.facebook }}"><i class="fa fa-facebook"></i></a></li>
									      		<li style="display: inline;"><a href="{{ member.twitter }}"><i class="fa fa-twitter"></i></a></li>
									      		<li style="display: inline;"><a href="{{ member.github }}"><i class="fa fa-github"></i></a></li>
									      	</ul>
									      </div>
									    </div>

									   {% else %}
									   	<div class="item">
									      <div class="col-xs-4">
									      	<img src="{{ member.image.url }}" class="member-img img-responsive">
									      	<span>{{ member.name }}</span><br>
									      	<span>{{ member.designation }}</span><br><br>
									      	<ul style="display: inline;">
									      		<li style="display: inline;"><a href="{{ member.facebook }}"><i class="fa fa-facebook"></i></a></li>
									      		<li style="display: inline;"><a href="{{ member.twitter }}"><i class="fa fa-twitter"></i></a></li>
									      		<li style="display: inline;"><a href="{{ member.github }}"><i class="fa fa-github"></i></a></li>
									      	</ul>
									      </div>
									    </div>

									    {% endif %}

									{% endfor %}
								</div>

									  <!-- Controls -->
									  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
									    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
									    <span class="sr-only">Previous</span>
									  </a>
									  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
									    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
									    <span class="sr-only">Next</span>
									  </a>
							</div>
						</div>
					</article>
				</div>
				<a href="#four" class="more">Learn More</a>
			</section>

		<!-- Four -->
			<section id="four" class="wrapper post bg-img" data-bg="{% static 'img/electrotech/banner5.jpg' %}">
				<div class="inner">
					<article class="box">
						<header>
							<h2>Events</h2>
						</header>
						<div class="content">
							<br>
							<h3>Upcoming event</h3>
							<h3>{{ event.title }}</h3>
							<h4>{{ event.date }} - {{ event.time }}</h4>
						</div>
						<footer>
							<a href="{% url 'electrotech:events' %}" class="button alt">All Events</a>
						</footer>
					</article>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h2>Contact Us</h2>

					<form id="contact_form">
					{% csrf_token %}

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name" required>
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email" required>
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="content" id="message" rows="6" placeholder="Message" required></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<ul class="icons">
						<li><a href="#" class="icon round fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon round fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon round fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>

					<div class="copyright">
						&copy; TechSpace (USICT)
					</div>

				</div>
			</footer>


<script type="text/javascript">

    $(document).on('submit', '#contact_form', function(e){
        e.preventDefault();

        var formData = $('#contact_form').serializeArray();
        formData.push({ name: "app_name", value: "electrotech" });
        

        $.ajax({
            type: 'POST',
            url: '/contact/submit/',
            data: formData,
            success:function(){
                clearMsg();
            }
        });
    });

    function clearMsg(){
        var s = document.getElementById('contact_form');
        v = "<div class='form_msg'><h2>Your message has been recorded.<br>Thank you for your response.</h2></div>"
        s.innerHTML = v;
        console.log("Success");
    }

</script>

{% endblock %}